version: "3.9"

services:
  frontend:
    build: ./

    container_name: battery-store

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    env_file:
      - ./env

